# Site settings
title: Junhee Pyo  # site title
description: >- # site description
  I'm a multidisciplinary designer and developer, with a strong interest in user experience, code, typography and accessibility.
lang: en-ko # default lang
timezone: Asia/Seoul # set your timezone
image: assets/img/img_profile-sns_profile.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/Junhee-p/junhee-p.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Junhee Pyo # author name
  bio: >- # tell to the world
    I ❤️ Design System, UX, Code, Life!
  username: Jay # general username
  github: Junhee-p # github username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  email: junheee.p@gmail.com # email adress
  avatar: /assets/img/img_profile_jay.png # change with your own avatar

# URL settings
url: "https://junhee-p.github.io" #
baseurl: /
permalink: /:title/
google_analytics: UA-110022099-1
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
future: true

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
